name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/softarv/telegrama/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - run: meson setup build
      - run: meson compile -C build
      - run: meson test -C build --print-errorlogs
